# Form implementation generated from reading ui file 'c:\Users\user\Desktop\wtfsc\desiner\chat_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChatWindow(object):
    def setupUi(self, ChatWindow):
        ChatWindow.setObjectName("ChatWindow")
        ChatWindow.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChatWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chatDisplay = QtWidgets.QTextBrowser(parent=ChatWindow)
        self.chatDisplay.setObjectName("chatDisplay")
        self.verticalLayout.addWidget(self.chatDisplay)
        self.messageInput = QtWidgets.QTextEdit(parent=ChatWindow)
        self.messageInput.setObjectName("messageInput")
        self.verticalLayout.addWidget(self.messageInput)
        self.sendButton = QtWidgets.QPushButton(parent=ChatWindow)
        self.sendButton.setObjectName("sendButton")
        self.verticalLayout.addWidget(self.sendButton)

        self.retranslateUi(ChatWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatWindow)

    def retranslateUi(self, ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatWindow.setWindowTitle(_translate("ChatWindow", "Chat"))
        self.sendButton.setText(_translate("ChatWindow", "Send"))
