# Form implementation generated from reading ui file 'c:\Users\user\Desktop\wtfsc\desiner\homework_table.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HomeworkTable(object):
    def setupUi(self, HomeworkTable):
        HomeworkTable.setObjectName("HomeworkTable")
        HomeworkTable.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(HomeworkTable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeworkTable = QtWidgets.QTableWidget(parent=HomeworkTable)
        self.homeworkTable.setObjectName("homeworkTable")
        self.homeworkTable.setColumnCount(3)
        self.homeworkTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.homeworkTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.homeworkTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.homeworkTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.homeworkTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addRowButton = QtWidgets.QPushButton(parent=HomeworkTable)
        self.addRowButton.setObjectName("addRowButton")
        self.horizontalLayout.addWidget(self.addRowButton)
        self.removeRowButton = QtWidgets.QPushButton(parent=HomeworkTable)
        self.removeRowButton.setObjectName("removeRowButton")
        self.horizontalLayout.addWidget(self.removeRowButton)
        self.saveButton = QtWidgets.QPushButton(parent=HomeworkTable)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(HomeworkTable)
        QtCore.QMetaObject.connectSlotsByName(HomeworkTable)

    def retranslateUi(self, HomeworkTable):
        _translate = QtCore.QCoreApplication.translate
        HomeworkTable.setWindowTitle(_translate("HomeworkTable", "Таблица Домашней Работы"))
        item = self.homeworkTable.horizontalHeaderItem(0)
        item.setText(_translate("HomeworkTable", "Предмет"))
        item = self.homeworkTable.horizontalHeaderItem(1)
        item.setText(_translate("HomeworkTable", "Задание"))
        item = self.homeworkTable.horizontalHeaderItem(2)
        item.setText(_translate("HomeworkTable", "Дедлайн"))
        self.addRowButton.setText(_translate("HomeworkTable", "Добавить строку"))
        self.removeRowButton.setText(_translate("HomeworkTable", "Удалить строку"))
        self.saveButton.setText(_translate("HomeworkTable", "Сохранить изменения"))
