# Form implementation generated from reading ui file 'c:\Users\user\Desktop\wtf2.0\desiner\progres_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_DBCreateWindow(object):
    def setupUi(self, DBCreateWindow):
        DBCreateWindow.setObjectName("DBCreateWindow")
        DBCreateWindow.resize(600, 353)
        DBCreateWindow.setMinimumSize(QtCore.QSize(600, 300))
        DBCreateWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        DBCreateWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        DBCreateWindow.setStyleSheet("background-color: rgb(0, 255, 127)")
        self.verticalLayout = QtWidgets.QVBoxLayout(DBCreateWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=DBCreateWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setStyleSheet("background-color: white; border-radius: 10px; ")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.message = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message.sizePolicy().hasHeightForWidth())
        self.message.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.message.setFont(font)
        self.message.setObjectName("message")
        self.verticalLayout_2.addWidget(self.message)
        self.class_2 = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.class_2.sizePolicy().hasHeightForWidth())
        self.class_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.class_2.setFont(font)
        self.class_2.setObjectName("class_2")
        self.verticalLayout_2.addWidget(self.class_2)
        self.progressBar = QtWidgets.QProgressBar(parent=self.widget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: LightSkyBlue;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.Direction.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.progressBar_2 = QtWidgets.QProgressBar(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_2.sizePolicy().hasHeightForWidth())
        self.progressBar_2.setSizePolicy(sizePolicy)
        self.progressBar_2.setMinimumSize(QtCore.QSize(0, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setStyleSheet("QProgressBar {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: LightSkyBlue;\n"
"}")
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_2.addWidget(self.progressBar_2)
        self.subject = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subject.sizePolicy().hasHeightForWidth())
        self.subject.setSizePolicy(sizePolicy)
        self.subject.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.subject.setFont(font)
        self.subject.setObjectName("subject")
        self.verticalLayout_2.addWidget(self.subject)
        self.line_2 = QtWidgets.QFrame(parent=self.widget)
        self.line_2.setStyleSheet("background-color: black")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.return_subjects_checkbox = QtWidgets.QCheckBox(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.return_subjects_checkbox.setFont(font)
        self.return_subjects_checkbox.setStyleSheet("CheckBox::indicator {\n"
"    width: 35px;\n"
"    height: 35px;\n"
"}")
        self.return_subjects_checkbox.setIconSize(QtCore.QSize(35, 35))
        self.return_subjects_checkbox.setObjectName("return_subjects_checkbox")
        self.verticalLayout_2.addWidget(self.return_subjects_checkbox)
        self.line = QtWidgets.QFrame(parent=self.widget)
        self.line.setStyleSheet("background-color: black")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=DBCreateWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("background-color: white; border-radius: 10px; ")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_start = QtWidgets.QPushButton(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout_3.addWidget(self.btn_start)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(DBCreateWindow)
        QtCore.QMetaObject.connectSlotsByName(DBCreateWindow)

    def retranslateUi(self, DBCreateWindow):
        _translate = QtCore.QCoreApplication.translate
        DBCreateWindow.setWindowTitle(_translate("DBCreateWindow", "Загрузка"))
        self.message.setText(_translate("DBCreateWindow", "Чтобы создать базы данных, нажмите на кнопку \"Начать\""))
        self.class_2.setText(_translate("DBCreateWindow", "Класс: "))
        self.progressBar.setFormat(_translate("DBCreateWindow", "%p%"))
        self.subject.setText(_translate("DBCreateWindow", "Предмет:"))
        self.return_subjects_checkbox.setText(_translate("DBCreateWindow", "Вернуть список учебных предметов в искодное состояние"))
        self.btn_start.setText(_translate("DBCreateWindow", "Начать"))
