# Form implementation generated from reading ui file 'c:\Users\user\Desktop\wtf2.0\desiner\ui_uilogin.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(450, 432)
        Login.setMinimumSize(QtCore.QSize(450, 400))
        Login.setMaximumSize(QtCore.QSize(450, 432))
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0.023, stop:0 rgba(255, 140, 140, 255), stop:1 rgba(94, 122, 255, 255));\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QFrame#frame{\n"
"    margin: 60px;\n"
"    border-radius: 20px;\n"
"    background-color: rgba(225, 228, 221, 120)\n"
"}\n"
"\n"
"QLineEdit{\n"
"    min-height: 45px;\n"
"    border-radius: 20px;\n"
"    background-color: #FFFFFF;\n"
"    padding-left: 20px;\n"
"    color: rgb(140, 140, 140);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(139, 142, 139);\n"
"}\n"
"\n"
"QPushButton#login_button{\n"
"    min-height: 45px;\n"
"    border-radius: 20px;\n"
"    background-color: rgb(140, 140, 140);\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton#login_button:hover{\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox{\n"
"    font-size: 10px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(95, 94, 108);\n"
"}\n"
"\n"
"QPushButton#forgot_button{\n"
"    border: 0px;\n"
"    font-style: italic;\n"
"    font-size: 10px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton#close_button{\n"
"    background-color: rgb(186, 0, 0);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton#minimize_button{\n"
"    background-color: rgb(226, 226, 0);\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_bar = QtWidgets.QFrame(parent=self.centralwidget)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.top_bar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(parent=self.top_bar)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(parent=self.top_bar)
        self.frame_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimize_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.minimize_button.setMaximumSize(QtCore.QSize(12, 12))
        self.minimize_button.setText("")
        self.minimize_button.setObjectName("minimize_button")
        self.horizontalLayout_3.addWidget(self.minimize_button)
        self.close_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.close_button.setMaximumSize(QtCore.QSize(12, 12))
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_3.addWidget(self.close_button)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.top_bar)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.login_button = QtWidgets.QPushButton(parent=self.frame)
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button)
        self.bottom_frame = QtWidgets.QFrame(parent=self.frame)
        self.bottom_frame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.bottom_frame)
        self.checkBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.forgot_button = QtWidgets.QPushButton(parent=self.bottom_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setItalic(True)
        self.forgot_button.setFont(font)
        self.forgot_button.setObjectName("forgot_button")
        self.horizontalLayout_2.addWidget(self.forgot_button)
        self.verticalLayout.addWidget(self.bottom_frame)
        self.verticalLayout_2.addWidget(self.frame)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.label_2.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:20pt;\">Sign In</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Login", "Email"))
        self.lineEdit_2.setPlaceholderText(_translate("Login", "Password"))
        self.login_button.setText(_translate("Login", "Sign In"))
        self.checkBox.setText(_translate("Login", "Remember me"))
        self.forgot_button.setText(_translate("Login", "Forgot Password"))
